source ~/.profile
source ~/.aliases
source ~/.term_config
source ~/.prompt_config

export LC_ALL=en_US.utf-8 
export LANG="$LC_ALL" 
export EDITOR=vim

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

[[ -s "/Users/yigitozkavci/.rvm/scripts/rvm" ]] && source "/Users/yigitozkavci/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -e /Users/yigitozkavci/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/yigitozkavci/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
if [ -e /home/yigit/.nix-profile/etc/profile.d/nix.sh ]; then . /home/yigit/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
