# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
export PATH=$PATH:~/.composer/vendor/bin
export PATH=$PATH:/Library/TeX/texbin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.6/bin
export PATH=$PATH:/Applications/ghc-7.10.3.app/Contents/bin
export PATH=$PATH:/Applications/llvm/bin
export PATH=$PATH:/usr/local/mysql/bin
export PATH=$PATH:~/.cabal/bin
export PATH=$PATH:~/Library/Haskell/bin
export PATH=$PATH:~/.bin
export GOPATH=~/Documents/Programming/GoWorkspace
export EVENT_NOKQUEUE=1
export NVM_DIR="~/.nvm"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="lambda"

source $ZSH/oh-my-zsh.sh

# User configuration

plugins=(git bundler osx rake ruby)
source ~/.profile
source ~/.aliases
source ~/.term_config
source ~/.prompt_config

export LC_ALL=en_US.utf-8 
export LANG="$LC_ALL" 
export EDITOR=vim

# Autocompletion for hub cli
fpath=(~/.zsh/completions $fpath)
autoload -U compinit && compinit
